plugins {
    id 'java'
}

group = 'com.movexa'
version = '1.0.0'
sourceCompatibility = '17'
targetCompatibility = '17'

repositories {
    mavenCentral()
    // Paper/Spigot depoları
    maven { url 'https://repo.papermc.io/repository/maven-public/' }
    maven { url 'https://hub.spigotmc.org/nexus/content/repositories/snapshots/' }
}

dependencies {
    // compileOnly: sunucu tarafı API'si, jar'a dahil edilmeyecek
    // Eğer sunucunuz 1.21.5 ise uygun sürümü burada kullanın (örnek: 1.21.5-R0.1-SNAPSHOT)
    compileOnly 'io.papermc.paper:paper-api:1.21.1-R0.1-SNAPSHOT'
}

jar {
    archiveBaseName = 'MovexaPrison'
    manifest {
        attributes(
            'Main-Class': 'com.movexa.prison.MovexaPrison'
        )
    }
}
